version: "3.7"

services:
  naming:
    image: "birdi7/ds_dfs_naming"
    build:
      context: .
      dockerfile: naming.dockerfile
    ports:
#      - 80:80
      - 8000:80
    depends_on:
      - db
    volumes:
      - ./logs:/tmp/

  storage:
    image: "birdi7/ds_dfs_storage"
    build:
      context: .
      dockerfile: storage.dockerfile
    volumes:
      - ./logs:/tmp/
      - /tmp/ds_dfs:/app/var/

#    deploy:
#      replicas: 10
#
    depends_on:
      - naming

  client:
    image: "birdi7/ds_dfs_client"
    build:
      context: .
      dockerfile: client.dockerfile

    command: bash
    volumes:
      - .:/client

    depends_on:
      - storage

  db:
    image: postgres
    environment:
      - POSTGRES_DB=naming
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
