version: "3.7"

services:
  naming:
    image: "birdi7/naming"
    build:
      context: .
      dockerfile: naming.dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./logs:/tmp/

  storage:
    image: "birdi7/storage"
    build:
      context: .
      dockerfile: storage.dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./logs:/tmp/

    depends_on:
      - naming

  db:
    image: postgres
    environment:
      - POSTGRES_DB=naming
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
