version: "3.7"

services:
  naming:
    image: "birdi7/ds_dfs_naming"
    build:
      context: .
      dockerfile: naming.dockerfile

    command: make naming_prod

    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./logs:/tmp/

    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.check-health.schedule: "@every 5s"
      ofelia.job-exec.check-health.command: "make check"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - naming
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  storage:
    image: "birdi7/ds_dfs_storage"
    build:
      context: .
      dockerfile: storage.dockerfile
    volumes:
      - ./logs:/tmp/
#      - /tmp/ds_dfs:/app/var/

    deploy:
      replicas: 3

    depends_on:
      - naming

    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.ss-sync.schedule: "@every 5s"
      ofelia.job-exec.ss-sync.command: "make ss_sync"


  client:
    image: "birdi7/ds_dfs_client"
    build:
      context: .
      dockerfile: client.dockerfile

    command: bash
    volumes:
      - ./client_data:/app/data

    depends_on:
      - storage

  db:
    image: postgres
    environment:
      - POSTGRES_DB=naming
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
