version: "3.7"

services:
  naming:
    image: "birdi7/naming"
    build:
      context: .
      dockerfile: naming.dockerfile
    ports:
      - 80:8000
    depends_on:
      - db
    volumes:
      - ./logs:/var/log/

  db:
    image: postgres
    environment:
      - POSTGRES_DB=naming
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
