# Generated by Django 3.1.2 on 2020-10-01 19:54

import core.utils.hashes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20201001_1922"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="owner_hash",
            field=models.TextField(
                default=core.utils.hashes.get_random_hash,
                max_length="10",
                verbose_name="Unique hash, only owner of the file knows it",
            ),
        ),
    ]
