# Generated by Django 3.1.2 on 2020-10-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_storedfile_owner_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storedfile",
            name="owner_hash",
        ),
    ]
