# Generated by Django 3.1.2 on 2020-10-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_storedfile_owner_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="meta",
            field=models.JSONField(default={}, verbose_name="Meta information about file"),
        ),
    ]
