# Generated by Django 3.1.2 on 2020-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20201003_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="size",
            field=models.IntegerField(null=True, verbose_name="Size of the file, in bytes"),
        ),
    ]
