# Generated by Django 3.1.2 on 2020-10-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20201003_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="size",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Size of the file, in bytes"),
        ),
    ]
