# Generated by Django 3.1.2 on 2020-10-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20201003_1618"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageserver",
            name="available_space",
            field=models.PositiveBigIntegerField(verbose_name="Available space on disk, in bytes"),
        ),
    ]
