# Generated by Django 3.1.2 on 2020-10-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20201003_1624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="meta",
            field=models.JSONField(blank=True, default=dict, verbose_name="Meta information about file"),
        ),
    ]
