# Generated by Django 3.1.2 on 2020-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="name",
            field=models.TextField(unique=True, verbose_name="File name"),
        ),
    ]
