# Generated by Django 3.1.2 on 2020-10-06 16:52
from core.models import StoredFile
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20201006_1652"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args: StoredFile.objects.create(name="/", size=None),
            lambda *args: StoredFile.objects.filter(name="/").delete(),
        )
    ]
