# Generated by Django 3.1.2 on 2020-10-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20201006_1834"),
        ("core", "0013_add_root_dir"),
    ]

    operations = []
